project:
    name: "Hakon CMS"
    
plugins:
    providers:
        loaded:
            - "Core\\Install\\Service\\InstallServiceProvider"
            - "Core\\Dashboard\\Service\\DashboardServiceProvider"
    aliases:
        loaded:
            pluginInstall: "Core\\Install\\Service\\InstallServiceProvider"
            pluginDashboard: "Core\\Dashboard\\Service\\DashboardServiceProvider"

templates:
    loaded: "default"

installation:
    status: "OK"
