#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Artisan
|--------------------------------------------------------------------------
|
| Here we are going to call Artisan to handle this request.
|
*/

require __DIR__.'/artisan';